"use client";

import {useEffect,useRef} from "react";
import type {PlayerAction,PlayerDnaSpot} from "@/data/player-dna-spots";
import styles from "./PlayerDnaPokerTable.module.css";

type Props={spot:PlayerDnaSpot;selectedAction:PlayerAction|null;onSequenceReady:(ready:boolean)=>void};
type ActionHistoryItem={position:string;action:string;value:number};
type SpotWithHistory=PlayerDnaSpot&{actionHistory?:ActionHistoryItem[]};
const positionRank:Record<string,number>={SB:0,BB:1,UTG:2,UTG1:3,"UTG+1":3,UTG2:4,"UTG+2":4,MP:5,MP1:5,MP2:6,"MP+1":6,LJ:7,HJ:8,CO:9,BTN:10};
function esc(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]??char))}
function cardMarkup(card:string){const rank=esc(card.slice(0,-1));const suit=esc(card.slice(-1));const red=suit==="♥"||suit==="♦";return `<div class="card ${red?"redc":"blackc"}"><span class="rank">${rank}</span><span class="suit">${suit}</span></div>`}
function stackLabel(value:number){return `${Number.isInteger(value)?value:value.toFixed(1)} BB`}
function orderedPlayersAroundHero(players:PlayerDnaSpot["players"],heroPosition:string){const sorted=[...players].sort((a,b)=>(positionRank[a.position]??99)-(positionRank[b.position]??99));const heroIndex=sorted.findIndex(player=>player.position===heroPosition);if(heroIndex<0)return sorted.filter(player=>!player.hero);return[...sorted.slice(heroIndex+1),...sorted.slice(0,heroIndex)].filter(player=>!player.hero)}
function seatPosition(index:number,opponentCount:number){const totalSeats=opponentCount+1;const angle=Math.PI/2+((index+1)*Math.PI*2/totalSeats);const left=50+47*Math.cos(angle);const top=50+43*Math.sin(angle);return`left:${left.toFixed(2)}%;top:${top.toFixed(2)}%`}
function actionSequenceForSpot(spot:PlayerDnaSpot,opponents:PlayerDnaSpot["players"]){const seatByPosition=new Map(opponents.map((player,seatIndex)=>[player.position,seatIndex]));const history=(spot as SpotWithHistory).actionHistory;if(history?.length)return history.flatMap(item=>{const seatIndex=seatByPosition.get(item.position);const player=opponents.find(candidate=>candidate.position===item.position);return seatIndex===undefined||!player?[]:[{player:{...player,action:item.action,value:item.value},seatIndex}]});return opponents.map((player,seatIndex)=>({player,seatIndex})).filter(({player})=>player.action!=="AGUARDA"&&player.action!=="---")}

export default function PlayerDnaPokerTable({spot,selectedAction,onSequenceReady}:Props){
  const hostRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    const host=hostRef.current;if(!host)return;
    const root=host.shadowRoot??host.attachShadow({mode:"open"});
    const hero=spot.players.find(player=>player.hero)??spot.players[0];
    const opponents=orderedPlayersAroundHero(spot.players,hero.position).slice(0,9);
    const actionSequence=actionSequenceForSpot(spot,opponents);
    const board=(spot.board??"").split(" ").filter(Boolean);const heroCards=spot.heroCards.split(" ").filter(Boolean);const sideTotal=(spot.pot.sides??[]).reduce((sum,pot)=>sum+pot.value,0);
    const seats=opponents.map((player,index)=>`<div class="seat" style="${seatPosition(index,opponents.length)}" data-seat="${index}" data-position="${esc(player.position)}"><div class="backs"><span></span><span></span></div><div class="plate"><b>${esc(player.position)}</b></div><div class="stack">${stackLabel(player.stack)}</div></div>`).join("");
    root.innerHTML=`<style>:host{display:block;width:100%}*{box-sizing:border-box}.scene{position:relative;width:min(100%,448px);aspect-ratio:.67/1;margin:0 auto;font-family:Arial,Helvetica,sans-serif;color:#fff}.table{position:absolute;inset:0 2.5%;border-radius:49%/16%;background:#111;box-shadow:inset 0 0 0 7px #080909}.felt{position:absolute;inset:10.1%;border-radius:47%/16%;background:radial-gradient(ellipse at 50% 35%,#25282b 0%,#0f1113 70%,#08090a 100%)}.seat{position:absolute;width:60px;text-align:center;z-index:8;transform:translate(-50%,-50%)}.seat.folded{display:none!important}.backs{height:34px;display:flex;justify-content:center;align-items:flex-end;gap:1px}.backs span{width:21px;height:31px;border:1px solid #fff;border-radius:3px;background:#dfe5ea}.plate{display:inline-flex;align-items:center;justify-content:center;min-width:48px;min-height:23px;padding:3px 5px;border-radius:6px;background:#111;border:1px solid #71614d}.plate b{font-size:9px}.stack{font-size:8px;font-weight:900}.pot{position:absolute;left:50%;top:36%;transform:translateX(-50%);padding:4px 10px;border-radius:10px;background:rgba(14,50,33,.9);font-weight:900;font-size:12px}.sidepot{position:absolute;left:50%;top:41%;transform:translateX(-50%);font-size:8px}.board{position:absolute;left:50%;top:47%;transform:translateX(-50%);display:flex;gap:3px}.card{width:37px;height:52px;border-radius:5px;background:#fff;padding:3px}.blackc{color:#050505}.redc{color:#ff1a1a}.rank{font-size:15px;font-weight:900}.suit{font-size:24px}.street{position:absolute;left:50%;top:56%;transform:translateX(-50%);font-size:9px}.heroaction{position:absolute;left:50%;bottom:21%;transform:translateX(-50%);padding:3px 8px;border-radius:999px;background:#edf0eb;color:#173324;font-size:8px;font-weight:900}.herostack{position:absolute;left:50%;bottom:10.5%;transform:translateX(-50%);font-size:10px;font-weight:900}.herocards{position:absolute;left:50%;bottom:-.5%;transform:translateX(-50%);display:flex;gap:2px}.heroplate{position:absolute;left:50%;bottom:-8.7%;transform:translateX(-50%);min-width:104px;padding:6px 10px;border-radius:8px;background:#7d130b;border:1px solid #c89446;text-align:center}.action{position:absolute;left:50%;top:69px;transform:translateX(-50%);background:#edf0eb;color:#173324;border-radius:999px;padding:3px 7px;font-size:7px;font-weight:900;white-space:nowrap}</style><div class="scene"><div class="table"><div class="felt">${seats}<div class="pot">POT ${stackLabel(spot.pot.main)}</div>${sideTotal>0?`<div class="sidepot">SIDE POT ${stackLabel(sideTotal)}</div>`:""}<div class="board">${board.map(cardMarkup).join("")}</div><div class="street">${esc(spot.street)}</div><div class="heroaction">${selectedAction?esc(selectedAction):"SUA AÇÃO"}</div><div class="herostack">${stackLabel(hero.stack)}</div><div class="herocards">${heroCards.map(cardMarkup).join("")}</div><div class="heroplate"><b>HERO · ${esc(hero.position)}</b><small>${stackLabel(hero.stack)}</small></div></div></div></div>`;
    onSequenceReady(true);
    const timers:number[]=[];
    const play=(step:number)=>{if(step>=actionSequence.length)return;const{player,seatIndex}=actionSequence[step];const seat=root.querySelector<HTMLElement>(`.seat[data-seat="${seatIndex}"]`);if(seat){seat.querySelector(".action")?.remove();const badge=document.createElement("div");badge.className="action";badge.textContent=player.value>0?`${player.action} ${stackLabel(player.value)}`:player.action;seat.appendChild(badge);if(player.action==="FOLD")timers.push(window.setTimeout(()=>seat.classList.add("folded"),180))}timers.push(window.setTimeout(()=>play(step+1),220))};
    if(actionSequence.length)timers.push(window.setTimeout(()=>play(0),80));
    return()=>timers.forEach(timer=>window.clearTimeout(timer));
  },[spot,selectedAction,onSequenceReady]);
  return <div ref={hostRef} className={styles.host} aria-label="MESA DE POKER ANIMADA PLAYER DNA"/>;
}
