"use client";

import {useEffect,useMemo,useState} from "react";
import {buildBalancedSpotSession} from "@/lib/player-dna-sampler";
import {buildPlayerDnaExchange} from "@/lib/player-dna-exchange";
import type {DnaDevelopmentReport} from "@/lib/player-dna-report";
import type {PlayerDnaAnswer} from "@/lib/player-dna";
import type {StackupSpotExchange,StackupTrainingPrescription} from "@/lib/stackup-exchange";
import {playerDnaSpots,type GameMode} from "@/data/player-dna-spots";
import {evolutionSummary,importLegacyHandReviews,readEvolutionLibrary,topLeakTags,upsertEvolutionEnvelope,type StackupEvolutionLibrary,type StackupEvolutionRecord} from "@/lib/stackup-evolution-store";

const PLAYER_DNA_KEY="stackup.player-dna.library.v3";const TRAINING_LAUNCH_KEY="stackup.training.launch.v1";const TRAINING_LAUNCH_EVENT="stackup:training-launch";
type LegacyDnaReport={id:string;name:string;mode:GameMode;target:number;sessionSeed:number;completedAt:number;answers:PlayerDnaAnswer[];development:DnaDevelopmentReport;result?:{label?:string;scores?:Record<string,number>}};

export default function StackupEvolutionWorkspace(){const[library,setLibrary]=useState<StackupEvolutionLibrary>({version:1,records:[]});const[open,setOpen]=useState(false);const[selectedId,setSelectedId]=useState<string|null>(null);const[launchMessage,setLaunchMessage]=useState("");const summary=useMemo(()=>evolutionSummary(library),[library]);const leakTags=useMemo(()=>topLeakTags(summary.activeLeaks),[summary.activeLeaks]);const selected=library.records.find(r=>r.id===selectedId)??null;useEffect(()=>{sync()},[]);function sync(){try{importLegacyHandReviews(localStorage);const raw=localStorage.getItem(PLAYER_DNA_KEY);if(raw){const parsed=JSON.parse(raw) as {reports?:LegacyDnaReport[]};for(const report of parsed.reports??[]){if(!report?.id||!report?.development||!Array.isArray(report.answers))continue;const spots=buildBalancedSpotSession(playerDnaSpots,report.mode,report.target,report.sessionSeed);const envelope=buildPlayerDnaExchange({reportId:report.id,reportName:report.name,mode:report.mode,completedAt:report.completedAt,answers:report.answers,spots,development:report.development});upsertEvolutionEnvelope(envelope,"PLAYER_DNA",report.name,localStorage)}}setLibrary(readEvolutionLibrary(localStorage))}catch{}}
 function launchTraining(item:StackupTrainingPrescription,record:StackupEvolutionRecord){const payload={version:1,id:`launch-${Date.now()}`,prescriptionId:item.id,analysisId:item.analysisId??null,leakId:item.leakId??null,sourceRecordId:record.id,title:item.title,reason:item.reason,mode:item.mode??null,street:item.street??null,positions:item.positions??[],trainingTags:item.trainingTags,conceptTags:item.conceptTags??[],targetSpots:item.targetSpots,difficultyMin:item.difficultyMin??null,difficultyMax:item.difficultyMax??null,timerSeconds:item.timerSeconds??null,reviewWrongAnswers:item.reviewWrongAnswers??true,createdAt:Date.now()};try{localStorage.setItem(TRAINING_LAUNCH_KEY,JSON.stringify(payload));window.dispatchEvent(new CustomEvent(TRAINING_LAUNCH_EVENT,{detail:payload}));setLaunchMessage(`TREINO PREPARADO · ${item.targetSpots} SPOTS · ${item.trainingTags.join(" · ")}`)}catch{setLaunchMessage("NÃO FOI POSSÍVEL PREPARAR O TREINO.")}}
 return <section style={{marginBottom:16,border:"1px solid rgba(92,187,126,.28)",borderRadius:16,padding:16,background:"rgba(7,20,12,.78)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><div className="eyebrow">STACKUP INTELLIGENCE</div><h3 style={{margin:"6px 0"}}>ANÁLISES & EVOLUÇÃO</h3><p style={{margin:0,opacity:.72,fontSize:12}}>PLAYER DNA, mãos, leaks, treinos e evolução no mesmo histórico.</p></div><div style={{display:"flex",gap:8}}><button onClick={sync}>ATUALIZAR</button><button className="primary" onClick={()=>{setOpen(v=>!v);if(open)setSelectedId(null)}}>{open?"FECHAR HISTÓRICO":"ABRIR HISTÓRICO"}</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8,marginTop:12}}><Info label="ANÁLISES" value={String(summary.records)}/><Info label="PLAYER DNA" value={String(summary.playerDna)}/><Info label="MÃOS" value={String(summary.handReviews)}/><Info label="TREINOS CONCLUÍDOS" value={String(summary.completedTraining.length)}/><Info label="LEAKS ATIVOS" value={String(summary.activeLeaks.length)}/><Info label="LEAKS RESOLVIDOS" value={String(summary.resolvedLeaks.length)}/><Info label="TREINOS PENDENTES" value={String(summary.pendingTraining.length)}/></div>{leakTags.length>0&&<div style={{marginTop:10,fontSize:12,opacity:.8}}>FOCOS ATUAIS: {leakTags.map(([tag,count])=>`${tag} (${count})`).join(" · ")}</div>}{launchMessage&&<div style={{marginTop:10,padding:10,border:"1px solid rgba(92,187,126,.25)",borderRadius:9,fontSize:12}}>{launchMessage}</div>}{selected&&<RecordDetail record={selected} onBack={()=>setSelectedId(null)} onLaunch={item=>launchTraining(item,selected)}/>} {open&&!selected&&<div style={{display:"grid",gap:8,marginTop:14}}>{library.records.length===0?<small>NENHUMA EVIDÊNCIA REGISTRADA AINDA.</small>:library.records.map(record=>{const result=record.envelope.trainingResults?.[0];const spots=record.envelope.spots?.length??result?.totalSpots??0;const leaks=record.envelope.leaks?.filter(l=>l.status!=="RESOLVIDO").length??0;const training=record.envelope.prescriptions?.filter(p=>p.status!=="CONCLUIDO").length??0;return <button type="button" key={record.id} onClick={()=>{setSelectedId(record.id);setOpen(true)}} style={{textAlign:"left",padding:12,border:"1px solid rgba(92,187,126,.16)",borderRadius:10,background:"rgba(255,255,255,.02)",color:"inherit"}}><strong>{record.title}</strong><small style={{display:"block",marginTop:5}}>{record.source} · {spots} SPOTS · {leaks} LEAKS · {training} TREINOS{result?` · ADERÊNCIA ${result.accuracy}%`:""}</small><small>ABRIR DETALHES →</small></button>})}</div>}</section>}
function RecordDetail({record,onBack,onLaunch}:{record:StackupEvolutionRecord;onBack:()=>void;onLaunch:(item:StackupTrainingPrescription)=>void}){const spot=record.envelope.spots?.[0];const leaks=record.envelope.leaks??[];const prescriptions=record.envelope.prescriptions??[];const dnaReport=readDnaReport(record);const result=record.envelope.trainingResults?.[0];return <div style={{marginTop:16,borderTop:"1px solid rgba(92,187,126,.18)",paddingTop:14}}><button onClick={onBack}>← LINHA DO TEMPO</button><h3>{record.title}</h3>{record.source==="TRAINING_APP"&&result?<TrainingDetail record={record}/>:record.source==="PLAYER_DNA"&&dnaReport?<PlayerDnaDetail report={dnaReport}/>:<HandDetail spot={spot}/>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8,marginTop:10}}><Info label="LEAKS" value={String(leaks.length)}/><Info label="TREINOS" value={String(prescriptions.length)}/><Info label="SPOTS" value={String(record.envelope.spots?.length??result?.totalSpots??0)}/></div>{leaks.map(leak=><div key={leak.id} style={{marginTop:8,padding:12,border:"1px solid rgba(255,170,80,.2)",borderRadius:10}}><small>{leak.severity} · {leak.status}</small><strong style={{display:"block"}}>{leak.title}</strong><p>{leak.description}</p></div>)}{prescriptions.map(item=><div key={item.id} style={{marginTop:8,padding:12,border:"1px solid rgba(92,187,126,.18)",borderRadius:10}}><small>{item.priority} · {item.status}</small><strong style={{display:"block",marginTop:4}}>{item.title}</strong><p style={{fontSize:12,opacity:.76}}>{item.targetSpots} SPOTS · {item.mode??"MISTO"} · {item.street??"TODAS STREETS"} · {item.trainingTags.join(" · ")}</p>{item.status!=="CONCLUIDO"&&<button type="button" className="primary" onClick={()=>onLaunch(item)}>INICIAR TREINO RECOMENDADO</button>}</div>)}</div>}
function TrainingDetail({record}:{record:StackupEvolutionRecord}){const result=record.envelope.trainingResults?.[0];const evolution=record.envelope.evolution?.[0];if(!result)return null;return <div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}><Info label="SPOTS" value={String(result.totalSpots)}/><Info label="MATCH MATRIZ" value={String(result.correctSpots)}/><Info label="DIVERGÊNCIAS" value={String(result.incorrectSpots??0)}/><Info label="ADERÊNCIA" value={`${result.accuracy}%`}/><Info label="QUALIDADE" value={result.score!=null?`${result.score}%`:"—"}/><Info label="CONFIANÇA EVOLUÇÃO" value={evolution?`${evolution.confidence}%`:"—"}/></div><small style={{display:"block",marginTop:9,opacity:.66}}>ADERÊNCIA = comparação com a matriz de pesos do PLAYER DNA. NÃO representa precisão GTO.</small>{evolution?.improvedLeaks.length?<p style={{fontSize:12}}>MELHORANDO: {evolution.improvedLeaks.join(" · ")}</p>:null}{evolution?.resolvedLeaks?.length?<p style={{fontSize:12}}>RESOLVIDOS: {evolution.resolvedLeaks.join(" · ")}</p>:null}</div>}
function PlayerDnaDetail({report}:{report:LegacyDnaReport}){return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}><Info label="PERFIL" value={report.development.archetype}/><Info label="EVOLUTION SCORE" value={`${report.development.evolutionScore}/100`}/><Info label="CONFIANÇA" value={`${report.development.confidence}%`}/><Info label="SPOTS" value={String(report.answers.length)}/></div>}
function HandDetail({spot}:{spot?:StackupSpotExchange}){if(!spot)return <p>DETALHES NÃO DISPONÍVEIS.</p>;return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}><Info label="MODALIDADE" value={spot.mode}/><Info label="STREET" value={spot.street}/><Info label="HERÓI" value={spot.heroPosition??"—"}/><Info label="AÇÃO" value={spot.selectedAction??"—"}/><Info label="ESPERADA" value={spot.expectedAction??"—"}/><Info label="RESULTADO" value={spot.decision?.outcome??"NAO_AVALIADA"}/></div>}
function readDnaReport(record:StackupEvolutionRecord):LegacyDnaReport|null{if(typeof window==="undefined"||record.source!=="PLAYER_DNA")return null;try{const raw=localStorage.getItem(PLAYER_DNA_KEY);const parsed=raw?JSON.parse(raw) as {reports?:LegacyDnaReport[]}:{};const sourceId=record.envelope.spots?.[0]?.sourceRecordId??record.id;return(parsed.reports??[]).find(r=>r.id===sourceId||r.id===record.id)??null}catch{return null}}
function Info({label,value}:{label:string;value:string}){return <div style={{padding:10,border:"1px solid rgba(92,187,126,.14)",borderRadius:9}}><small style={{display:"block",opacity:.55}}>{label}</small><b>{value}</b></div>}
