import type {GameMode,PlayerAction,PlayerDnaSpot} from "@/data/player-dna-spots";
import {solverSpotFingerprint,type SolverReferencedSpot} from "@/lib/player-dna-solver-reference";

export type ExactComboFrequencies=Partial<Record<PlayerAction,number>>;
export type ExactComboNode={id:string;street:"FLOP"|"TURN"|"RIVER"|"flop"|"turn"|"river";positionState:"IP"|"OOP";potType:string;texture:string;board:string|string[];rootPot:number;effectiveStack:number;resolvedPath:string[];actions:string[];combos:Record<string,ExactComboFrequencies>};
export type ExactComboBank={schemaVersion:number|string;source:string;scope:string;nodeCount:number;exactComboDecisionCount:number;rejectedBoardCollisionCombos:number;nodes:ExactComboNode[]};

const SUITS=["s","h","d","c"] as const;
const GLYPH:Record<string,string>={s:"♠",h:"♥",d:"♦",c:"♣"};
type Candidate={node:ExactComboNode;combo:string;suitIndex:number;key:string;fingerprint:string};
const candidateCache=new Map<string,Candidate[]>();
const orderCache=new Map<string,Candidate[]>();
function hashText(value:string){let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619)}return hash>>>0}
function rng(seed:number){let state=(seed||1)>>>0;return()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296}}
function shuffle<T>(items:T[],seed:number){const out=[...items],random=rng(seed);for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function suitPermutation(index:number){const source=[...SUITS];const out:string[][]=[];function walk(prefix:string[],remaining:string[]){if(!remaining.length){out.push(prefix);return}for(let i=0;i<remaining.length;i++)walk([...prefix,remaining[i]],[...remaining.slice(0,i),...remaining.slice(i+1)])}walk([],source);return new Map(SUITS.map((s,i)=>[s,out[((index%24)+24)%24][i]]))}
function parseCards(value:string|string[]){return Array.isArray(value)?value:value.replaceAll(","," ").trim().split(/\s+/).filter(Boolean)}
function mapCard(raw:string,map:Map<string,string>){const rank=raw.slice(0,-1),suit=raw.slice(-1).toLowerCase();return`${rank}${GLYPH[map.get(suit)??suit]??suit}`}
function mapCards(value:string|string[],map:Map<string,string>){return parseCards(value).map(card=>mapCard(card,map)).join(" ")}
function actionFamily(value:string){const action=value.toUpperCase().replaceAll("_","-");if(action.startsWith("ALLIN")||action.startsWith("ALL-IN")||action.startsWith("ALL IN"))return"ALL-IN";if(action.startsWith("RAISE"))return"RAISE";if(action.startsWith("BET"))return"BET";if(action.startsWith("CALL"))return"CALL";if(action.startsWith("CHECK"))return"CHECK";if(action.startsWith("FOLD"))return"FOLD";return action.split(" ")[0]}
function actionAmount(value:string){const match=value.match(/(-?\d+(?:\.\d+)?)/);return match?Number(match[1]):0}
function positions(node:ExactComboNode){const match=node.id.match(/-(bb|sb|btn|co|hj|lj|mp|utg)-vs-(bb|sb|btn|co|hj|lj|mp|utg)-/i);if(match)return{hero:match[1].toUpperCase(),villain:match[2].toUpperCase()};return node.positionState==="IP"?{hero:"BTN",villain:"BB"}:{hero:"BB",villain:"BTN"}}
function modeOf(node:ExactComboNode):GameMode{return node.id.startsWith("mtt-")?"TORNEIO":"CASH"}
function normalizedFrequencies(value:ExactComboFrequencies){const clean:ExactComboFrequencies={};let total=0;for(const [action,weight] of Object.entries(value) as [PlayerAction,number][])if(Number.isFinite(weight)&&weight>0){clean[action]=weight;total+=weight}if(total<=0)return clean;for(const action of Object.keys(clean) as PlayerAction[])clean[action]=Math.round(((clean[action]??0)*10000)/total)/100;return clean}
function legalActions(freq:ExactComboFrequencies,lastAction:string):PlayerAction[]{const keys=(Object.keys(freq) as PlayerAction[]).filter(action=>(freq[action]??0)>0);const base=(lastAction==="BET"||lastAction==="RAISE"||lastAction==="ALL-IN")?["FOLD","CALL","RAISE","ALL-IN"] as PlayerAction[]:["CHECK","BET","RAISE","ALL-IN"] as PlayerAction[];return base.filter(action=>keys.includes(action)||action==="ALL-IN")}
function spotFromCombo(node:ExactComboNode,combo:string,suitIndex:number):SolverReferencedSpot{const map=suitPermutation(suitIndex),pos=positions(node),mode=modeOf(node),resolved=node.resolvedPath??[],rawLast=resolved.at(-1)??"CHECK",lastAction=actionFamily(rawLast),facingValue=(lastAction==="BET"||lastAction==="RAISE"||lastAction==="ALL-IN")?actionAmount(rawLast):0,frequencies=normalizedFrequencies(node.combos[combo]??{}),street=node.street.toUpperCase() as PlayerDnaSpot["street"];const base:PlayerDnaSpot={id:`exact-${node.id}-${combo}-${suitIndex.toString(36)}`,mode,...(mode==="TORNEIO"?{gameProfile:"MTT REGULAR" as const,anteMode:"NONE" as const}:{}),street,heroCards:mapCards(combo,map),board:mapCards(node.board,map),players:[{position:pos.hero,stack:node.effectiveStack,action:"---",value:0,hero:true},{position:pos.villain,stack:node.effectiveStack,action:lastAction,value:facingValue}],pot:{main:Math.round((node.rootPot+facingValue)*100)/100},scenario:[mode,node.potType,node.positionState,"HU","SOLVER VALIDATED"],prompt:`${pos.villain} ${lastAction}${facingValue>0?` ${facingValue} BB`:""}. HERO EM ${pos.hero}. QUAL É A MELHOR DECISÃO?`,actions:legalActions(frequencies,lastAction),weights:{}};return{...base,solverReference:{kind:"TEXASSOLVER_EXACT_COMBO",validated:true,frequencies,spotFingerprint:solverSpotFingerprint(base),nodeId:`${node.id}:${combo}`}}}
function uniqueCandidates(bank:ExactComboBank,mode:GameMode|"ALEATORIO"){const cacheKey=`${bank.source}|${bank.exactComboDecisionCount}|${mode}`;const cached=candidateCache.get(cacheKey);if(cached)return cached;const eligible=bank.nodes.filter(node=>mode==="ALEATORIO"||modeOf(node)===mode),out:Candidate[]=[],seen=new Set<string>();for(const node of eligible)for(const combo of Object.keys(node.combos))for(let suitIndex=0;suitIndex<24;suitIndex++){const spot=spotFromCombo(node,combo,suitIndex);const fingerprint=spot.solverReference!.spotFingerprint;if(seen.has(fingerprint))continue;seen.add(fingerprint);out.push({node,combo,suitIndex,key:`${node.id}|${combo}|${suitIndex}`,fingerprint})}if(candidateCache.size>=4)candidateCache.delete(candidateCache.keys().next().value as string);candidateCache.set(cacheKey,out);return out}
export function exactComboBankCapacity(bank:ExactComboBank,mode?:GameMode){return uniqueCandidates(bank,mode??"ALEATORIO").length}
function orderedCandidates(bank:ExactComboBank,mode:GameMode|"ALEATORIO",seed:number){const cacheKey=`${bank.source}|${bank.exactComboDecisionCount}|${mode}|${seed}`;const cached=orderCache.get(cacheKey);if(cached)return cached;const ordered=shuffle(uniqueCandidates(bank,mode),hashText(`${seed}:${mode}`));if(orderCache.size>=4)orderCache.delete(orderCache.keys().next().value as string);orderCache.set(cacheKey,ordered);return ordered}
export function buildExactComboSession(bank:ExactComboBank,mode:GameMode|"ALEATORIO",count:number,seed=Date.now(),seenFingerprints:Iterable<string>=[]){if(count<=0)return{spots:[] as SolverReferencedSpot[],requested:count,capacity:0,coveragePct:100,keys:[] as string[]};const seen=new Set(seenFingerprints),ordered=orderedCandidates(bank,mode,seed),available=seen.size?ordered.filter(item=>!seen.has(item.fingerprint)):ordered,selected=available.slice(0,count),spots=selected.map(item=>spotFromCombo(item.node,item.combo,item.suitIndex));return{spots,requested:count,capacity:available.length,coveragePct:spots.length===count?100:Math.round((spots.length/Math.max(1,count))*10000)/100,keys:selected.map(item=>item.key)}}
